# Site settings
title: "parkeratkins.ca"
description: "Full Stack Software Developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Parker Atkins"
resume_title:                   "Full Stack Web Developer"
resume_contact_email:           "parker.cattell.atkins@gmail.com"
resume_contact_telephone:       "(604)928-3539"
resume_contact_address:         "1359 St Patrick Street, Victoria"
resume_header_contact_info: "1359 St Patrick Street, Victoria | (604)928-3539 | parker_atkins@hotmail.com"
resume_header_intro: "<p>Hi, I'm Parker. I am a professional full stack web developer specialized in modern front end javascript technologies.  I am highly motivated, very organized and enjoy working in innovative development teams. Currently, I am seeking a challenging and exciting new work opportunity. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/pcatkins"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/parker-atkins-54b00868"
  resume_instagram_url:         "https://www.instagram.com/parkeratkins/"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Add plugin for site map
plugins:
  - jekyll-sitemap

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
